name: Run LinkedIn Bot Every Hour

on:
  schedule:
    - cron: '0 * * * *' # 매 정각 실행
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Debug file list
        run: |
          ls -al
          ls -al linkedinbot.py

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- (필수) Chrome 설치 스텝 ---
      - name: Install Chrome
        run: |
          sudo apt-get update
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
          google-chrome --version  # 설치된 Chrome 버전 확인

      - name: Debug Chrome installation
        run: |
          which google-chrome
          google-chrome --version
          ls -la /usr/bin/google-chrome*

      - name: Debug network conditions
        continue-on-error: true # 오류가 발생해도 계속 진행
        run: |
          ping -c 4 linkedin.com || echo "Ping failed but continuing..."
          curl -I --proxy ${{ secrets.HTTP_PROXY }} https://www.linkedin.com

      - name: Install additional dependencies for LinkedIn
        run: |
          sudo apt-get install -y xvfb
          pip install pyvirtualdisplay

      # LinkedIn Bot 실행 단계 수정
      - name: Run LinkedIn Bot with Xvfb and Proxy
        env:
          LINKEDIN_GOOGLESHEET_API: ${{ secrets.LINKEDIN_GOOGLESHEET_API }}
          LINKEDIN_EMAIL: ${{ secrets.LINKEDIN_EMAIL }}
          LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
          DISPLAY: ':99'
          # 프록시 환경변수 추가
          HTTP_PROXY: ${{ secrets.HTTP_PROXY }}
          HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}
        run: |
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          sleep 3
          python linkedinbot.py

      - name: List files after run (debug)
        run: ls -al

      - name: Upload all screenshots and logs
        uses: actions/upload-artifact@v4
        if: ${{ always() }} # 성공/실패 상관없이 항상 실행
        with:
          name: debug-files
          path: |
            *.png
            *.html
            *.log
            linkedin_cookies.pkl
          if-no-files-found: ignore

      - name: Get current IP
        run: |
          curl -s https://api.ipify.org
          # 또는
          curl -s http://checkip.amazonaws.com
