name: Run LinkedIn Bot Every Hour

on:
  schedule:
    - cron: '0 * * * *' # 매 정각 실행
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Debug file list
        run: |
          ls -al
          ls -al linkedinbot.py

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- (필수) Chrome 설치 스텝 ---
      - name: Install Chrome
        run: |
          sudo apt-get update
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
          google-chrome --version  # 설치된 Chrome 버전 확인

      - name: Run LinkedIn Bot
        env:
          LINKEDIN_GOOGLESHEET_API: ${{ secrets.LINKEDIN_GOOGLESHEET_API }}
          LINKEDIN_EMAIL: ${{ secrets.LINKEDIN_EMAIL }}
          LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
        run: |
          python linkedinbot.py

      - name: List files after run (debug)
        run: ls -al

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        if: ${{ always() }} # 실패해도 실행
        with:
          name: debug-screenshot
          path: screen.png
          if-no-files-found: ignore

      - name: Debug Chrome installation
        run: |
          which google-chrome
          google-chrome --version
          ls -la /usr/bin/google-chrome*
